export const items = [
  {
    id: 1,
    category: '흑백',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 2,
    category: '카드',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 3,
    category: '컬러',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 4,
    category: '카드',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 5,
    category: '엽서',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 6,
    category: '엽서',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 7,
    category: '컬러',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 8,
    category: '엽서',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 9,
    category: '컬러',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 10,
    category: '카드',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 11,
    category: '엽서',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 12,
    category: '엽서',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 13,
    category: '흑백',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 14,
    category: '흑백',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 15,
    category: '컬러',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 16,
    category: '카드',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 17,
    category: '엽서',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 18,
    category: '엽서',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 19,
    category: '흑백',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
  {
    id: 20,
    category: '흑백',
    productImage: '/images/main_img.svg',
    productTitle: '인기상품',
    productSubTitle: '오늘의 인기상품을 둘러보세요',
    productPrice: '5,000원',
    productStarRate: '5.0',
    productReviewCount: '총 리뷰(100)',
  },
];